/* HOLO DECK COMPONENT */
(function(w){var U=w.UmerPortfolio,D=U.Data,Q=U.Utils;Q.ready(function(){
var wrap=document.getElementById('ringWrap'),ring=document.getElementById('ring');if(!wrap||!ring)return;var projects=D.HOLO_PROJECTS,live=D.HOLO_LIVE;ring.innerHTML='';var cards=[];
projects.forEach(function(p,i){var a=document.createElement('a');a.className='rcard';a.href=p[5]==='live'?(live[p[0]]||'#'):(p[5]==='internal'?'#commerce':'#');if(p[5]==='live')a.target='_blank';a.rel='noopener';a.dataset.accent=p[6];a.dataset.index=i;a.dataset.key=p[0];a.innerHTML='<img src="'+p[3]+'" alt="'+p[1]+'" loading="lazy"><span class="rn">'+p[1]+'</span><span class="rt">'+p[2]+' · '+(p[5]==='local'?'LOCAL BUILD':(p[5]==='internal'?'OPEN':'LIVE ↗'))+'</span>';if(p[4]){var v=document.createElement('video');v.muted=true;v.loop=true;v.playsInline=true;v.preload='none';v.setAttribute('aria-hidden','true');v.dataset.video=p[4];v.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:top;opacity:0;z-index:1;pointer-events:none;mix-blend-mode:screen;transition:opacity .45s';a.appendChild(v)}ring.appendChild(a);cards.push(a)});
var meta=document.createElement('div');meta.className='ring-meta';meta.innerHTML='<div class="ring-meta-main"><b id="ringMetaTitle">WEBCUT PRO</b><small id="ringMetaSub">BROWSER NLE · LIVE SYSTEM</small></div><div class="ring-meta-signal"><i></i><span id="ringMetaStatus">LIVE BUILD</span></div>';wrap.insertAdjacentElement('afterend',meta);
var current=0,velocity=0,dragging=false,startX=0,startA=0,lastX=0,spread=innerWidth<800?245:292,fan=7,depth=44;function normalize(n){n%=projects.length;return n<0?n+projects.length:n}function shortest(i){var d=i-current,n=projects.length;if(d>n/2)d-=n;if(d<-n/2)d+=n;return d}function setMeta(){var p=projects[normalize(Math.round(current))],title=document.getElementById('ringMetaTitle'),sub=document.getElementById('ringMetaSub'),st=document.getElementById('ringMetaStatus');if(title)title.textContent=p[1];if(sub)sub.textContent=p[2]+' · '+(p[5]==='local'?'LOCAL BUILD':p[5]==='internal'?'INTERNAL EXPERIENCE':'LIVE SYSTEM');if(st)st.textContent=p[5]==='local'?'NOT HOSTED':p[5]==='internal'?'INTERNAL BUILD':'LIVE BUILD'}
function render(){var active=normalize(Math.round(current));cards.forEach(function(card,i){var d=shortest(i),ad=Math.abs(d),x=d*spread,z=Math.max(-260,300-ad*depth),ry=d*fan,sc=Math.max(.72,1-ad*.065),op=ad>6?0:Math.max(.16,1-ad*.11);card.style.transform='translateX('+x.toFixed(1)+'px) translateZ('+z.toFixed(1)+'px) rotateY('+(-ry).toFixed(2)+'deg) scale('+sc.toFixed(3)+')';card.style.zIndex=String(100-Math.round(ad*4));card.style.opacity=String(op);card.classList.toggle('is-active',i===active);var v=card.querySelector('video');if(v){if(!v.src)v.src=v.dataset.video;if(i===active&&!dragging){v.play().then(function(){v.style.opacity='.18'}).catch(function(){})}else{v.pause();v.style.opacity='0'}}});setMeta()}
function go(delta){current=normalize(Math.round(current)+delta);render()}function snap(){current=normalize(Math.round(current));render()}
wrap.addEventListener('pointerdown',function(e){dragging=true;startX=e.clientX;lastX=e.clientX;startA=current;velocity=0;try{wrap.setPointerCapture(e.pointerId)}catch(err){}});wrap.addEventListener('pointermove',function(e){if(!dragging)return;var dx=e.clientX-lastX;lastX=e.clientX;velocity=dx*.018;current=startA-(e.clientX-startX)/spread;render()});function release(){if(!dragging)return;dragging=false;current-=velocity*2.2;snap()}wrap.addEventListener('pointerup',release);wrap.addEventListener('pointercancel',release);wrap.addEventListener('wheel',function(e){e.preventDefault();go(e.deltaY>0?1:-1)},{passive:false});document.addEventListener('keydown',function(e){if(e.target&&/input|textarea|select/i.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();go(1)}else if(e.key==='ArrowLeft'){e.preventDefault();go(-1)}});cards.forEach(function(card,i){card.addEventListener('click',function(e){var d=Math.abs(shortest(i));if(d>.35){e.preventDefault();current=i;render();return}if(projects[i][5]==='local'){e.preventDefault();if(window.openCase)window.openCase(projects[i][0]);else{var idx=document.querySelector('.idx[data-case="'+projects[i][0]+'"]');if(idx)idx.click()}}})});var last=performance.now();function auto(t){var dt=Math.min(32,t-last);last=t;if(!dragging){velocity*=.94;if(Math.abs(velocity)<.002)velocity=.012;current+=velocity*dt/16;render()}requestAnimationFrame(auto)}render();requestAnimationFrame(auto);U.Components=U.Components||{};U.Components.holoDeck={render:render,go:go,getCurrent:function(){return projects[normalize(Math.round(current))]}};
});})(window);
